# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [start-example-workflow]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: bitbucket.org
          private-key: ${{ secrets.SSH_PRIVATE_KEY_BITBUCKET }}
          private-key-name: bitbucket
          
      - name: Clone Bitbucket repository
        run: git clone git@bitbucket.org:ridvanaltun/card-collection.git
